package chanaka.gui;

import chanaka.dao.ActivitiesDAO;
import chanaka.dao.ComeToSchoolByDAO;
import chanaka.dao.GramaNiladhariDivisionsDAO;
import chanaka.dao.HousesDAO;
import chanaka.dao.ReligionsDAO;
import chanaka.dao.StudentDAO;
import chanaka.data.Student;
import common.validation.Validator;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.Date;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import malith.login.core.PasswordUtils;
import prabath.dao.NotificationDAO;
import prabath.data.Notification;
import prabath.data.Teacher;

public class AddOrEditStudent extends javax.swing.JDialog {

    StudentDAO studentDAO;
    private Student selectedStudent;
    private String previousAdmissionNumber;
    boolean This_is_AddMode_but_not_EditMode;
    int accessPriviledge;
    NotificationDAO notificationDao;
    boolean notificationMode;
    Teacher teacher;
    ActivitiesDAO activitiesDAO;
    String NIC;

    Validator validater;

    public AddOrEditStudent(java.awt.Frame parent, boolean modal, StudentDAO studentDao) {

        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        studentDAO = studentDao;
        This_is_AddMode_but_not_EditMode = true;
        this.validater = new Validator();

    }

    public AddOrEditStudent(java.awt.Frame parent, boolean modal, StudentDAO studentDao, Student student) throws IOException, SQLException {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        studentDAO = studentDao;
        this.previousAdmissionNumber = student.getAdmissionNumber();
        this.selectedStudent = student;
        This_is_AddMode_but_not_EditMode = false;
        this.validater = new Validator();

        notificationDao = new NotificationDAO(studentDao.getMyConn());
        activitiesDAO = new ActivitiesDAO(studentDao.getMyConn());
        populateData(student);
        btnAdd.setText("Save");
        accessPriviledge = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupGender = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNameWithInitial = new javax.swing.JTextField();
        txtFullnameEnglish = new javax.swing.JTextField();
        rdoMale = new javax.swing.JRadioButton();
        rdoFemale = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtTelephone = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtFullNameSinhala = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtClassOfAdmission = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtAdmissionNo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        dchBirthDate = new com.toedter.calendar.JDateChooser();
        dchDateOfAdmission = new com.toedter.calendar.JDateChooser();
        cboReligion = new javax.swing.JComboBox();
        cboHouse = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        FatherNametxt = new javax.swing.JTextField();
        MotherNametxt = new javax.swing.JTextField();
        FatherJobtxt = new javax.swing.JTextField();
        MotherJobtxt = new javax.swing.JTextField();
        FatherWorkPlacetxt = new javax.swing.JTextField();
        MotherWorkPlacetxt = new javax.swing.JTextField();
        FatherWorkAddresstxt = new javax.swing.JTextField();
        MotherWorkAddresstxt = new javax.swing.JTextField();
        FatherWorkTelephonetxt = new javax.swing.JTextField();
        FatherHomeTelephonetxt = new javax.swing.JTextField();
        FatherMobiletxt = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        MotherWorkTelephonetxt = new javax.swing.JTextField();
        MotherHomeTelephonetxt = new javax.swing.JTextField();
        MotherMobiletxt = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BroSis1Nametxt = new javax.swing.JTextField();
        BroSis2Nametxt = new javax.swing.JTextField();
        BroSis3Nametxt = new javax.swing.JTextField();
        BroSis4Nametxt = new javax.swing.JTextField();
        BroSis5Nametxt = new javax.swing.JTextField();
        BroSis1AdmissionNumbertxt = new javax.swing.JTextField();
        BroSis2AdmissionNumbertxt = new javax.swing.JTextField();
        BroSis3AdmissionNumbertxt = new javax.swing.JTextField();
        BroSis4AdmissionNumbertxt = new javax.swing.JTextField();
        BroSis5AdmissionNumbertxt = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        cboGramaVasama = new javax.swing.JComboBox();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        cboComeToSchoolBy = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add or edit student details");
        setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        setPreferredSize(new java.awt.Dimension(1366, 730));
        setResizable(false);

        jScrollPane1.setPreferredSize(new Dimension(Toolkit.getDefaultToolkit().getScreenSize().width, Toolkit.getDefaultToolkit().getScreenSize().height));

        jLabel2.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel2.setText("Name with initials :");

        jLabel3.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel3.setText("Full name (English) :");

        jLabel4.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel4.setText("Gender :");

        txtNameWithInitial.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N

        txtFullnameEnglish.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        txtFullnameEnglish.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFullnameEnglishKeyReleased(evt);
            }
        });

        buttonGroupGender.add(rdoMale);
        rdoMale.setText("Male");

        buttonGroupGender.add(rdoFemale);
        rdoFemale.setText("Female");

        jLabel5.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel5.setText("Date of birth :");

        jLabel11.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel11.setText("Address :");

        txtAddress.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel12.setText("Tel :");

        txtTelephone.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        txtTelephone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelephoneFocusLost(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel13.setText("Date of admission :");

        btnAdd.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel9.setText("Full name (සිංහල):");

        txtFullNameSinhala.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel15.setText("House :");

        jLabel20.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel20.setText("Religion :");

        txtClassOfAdmission.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel23.setText("Class of admission :");

        txtAdmissionNo.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        txtAdmissionNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdmissionNoActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel10.setText("Admission number :");

        dchBirthDate.setDateFormatString("yyyy/MM/d");
        dchBirthDate.setMaxSelectableDate(new java.util.Date());
        dchBirthDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dchBirthDateFocusLost(evt);
            }
        });
        dchBirthDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dchBirthDatePropertyChange(evt);
            }
        });

        dchDateOfAdmission.setDateFormatString("yyyy/MM/d");
        dchDateOfAdmission.setMaxSelectableDate(new java.util.Date());
        dchDateOfAdmission.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dchDateOfAdmissionFocusLost(evt);
            }
        });

        cboReligion.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N

        cboHouse.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel6.setText("Name :");

        jLabel8.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel8.setText("Mother's details");

        jLabel14.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel14.setText("Job :");

        jLabel16.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel16.setText("Work place :");

        jLabel17.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel17.setText("Work address :");

        jLabel18.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel18.setText("Telephone :");

        FatherNametxt.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N

        MotherNametxt.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N

        FatherJobtxt.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        FatherJobtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FatherJobtxtActionPerformed(evt);
            }
        });

        MotherJobtxt.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N

        FatherWorkPlacetxt.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N

        MotherWorkPlacetxt.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N

        FatherWorkAddresstxt.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N

        MotherWorkAddresstxt.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N

        FatherWorkTelephonetxt.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        FatherWorkTelephonetxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                FatherWorkTelephonetxtFocusLost(evt);
            }
        });
        FatherWorkTelephonetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FatherWorkTelephonetxtActionPerformed(evt);
            }
        });

        FatherHomeTelephonetxt.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        FatherHomeTelephonetxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                FatherHomeTelephonetxtFocusLost(evt);
            }
        });
        FatherHomeTelephonetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FatherHomeTelephonetxtActionPerformed(evt);
            }
        });

        FatherMobiletxt.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        FatherMobiletxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                FatherMobiletxtFocusLost(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Iskoola Pota", 0, 11)); // NOI18N
        jLabel19.setText("House :");

        jLabel21.setFont(new java.awt.Font("Iskoola Pota", 0, 11)); // NOI18N
        jLabel21.setText("Mobile :");

        jLabel22.setFont(new java.awt.Font("Iskoola Pota", 0, 11)); // NOI18N
        jLabel22.setText("Work :");

        MotherWorkTelephonetxt.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        MotherWorkTelephonetxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                MotherWorkTelephonetxtFocusLost(evt);
            }
        });

        MotherHomeTelephonetxt.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        MotherHomeTelephonetxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                MotherHomeTelephonetxtFocusLost(evt);
            }
        });
        MotherHomeTelephonetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MotherHomeTelephonetxtActionPerformed(evt);
            }
        });

        MotherMobiletxt.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        MotherMobiletxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                MotherMobiletxtFocusLost(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Iskoola Pota", 0, 11)); // NOI18N
        jLabel24.setText("House ;");

        jLabel25.setFont(new java.awt.Font("Iskoola Pota", 0, 11)); // NOI18N
        jLabel25.setText("Mobile :");

        jLabel26.setFont(new java.awt.Font("Iskoola Pota", 0, 11)); // NOI18N
        jLabel26.setText("Work ;");

        jComboBox1.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Father's details", "Guardian's details" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel7.setText("Details of brothers and sisters in this school :");

        jLabel27.setFont(new java.awt.Font("Iskoola Pota", 1, 24)); // NOI18N
        jLabel27.setText("Student details");

        jLabel1.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel1.setText("Name :");

        BroSis1Nametxt.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N

        BroSis2Nametxt.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N

        BroSis3Nametxt.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N

        BroSis4Nametxt.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N

        BroSis5Nametxt.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N

        BroSis1AdmissionNumbertxt.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        BroSis1AdmissionNumbertxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                BroSis1AdmissionNumbertxtFocusLost(evt);
            }
        });
        BroSis1AdmissionNumbertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BroSis1AdmissionNumbertxtActionPerformed(evt);
            }
        });

        BroSis2AdmissionNumbertxt.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        BroSis2AdmissionNumbertxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                BroSis2AdmissionNumbertxtFocusLost(evt);
            }
        });
        BroSis2AdmissionNumbertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BroSis2AdmissionNumbertxtActionPerformed(evt);
            }
        });

        BroSis3AdmissionNumbertxt.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        BroSis3AdmissionNumbertxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                BroSis3AdmissionNumbertxtFocusLost(evt);
            }
        });
        BroSis3AdmissionNumbertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BroSis3AdmissionNumbertxtActionPerformed(evt);
            }
        });

        BroSis4AdmissionNumbertxt.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        BroSis4AdmissionNumbertxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                BroSis4AdmissionNumbertxtFocusLost(evt);
            }
        });
        BroSis4AdmissionNumbertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BroSis4AdmissionNumbertxtActionPerformed(evt);
            }
        });

        BroSis5AdmissionNumbertxt.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        BroSis5AdmissionNumbertxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                BroSis5AdmissionNumbertxtFocusLost(evt);
            }
        });
        BroSis5AdmissionNumbertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BroSis5AdmissionNumbertxtActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel30.setText("Admission Number :");

        cboGramaVasama.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N

        jLabel31.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel31.setText("Grama Niladhari Division :");

        jLabel32.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel32.setText("Way of coming to school by :");

        cboComeToSchoolBy.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N

        jButton1.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton2.setText("Reload");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton3.setText("Reload");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton4.setText("Reload");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton5.setText("Reload");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(264, 264, 264))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel15)
                            .addComponent(jLabel13)
                            .addComponent(jLabel23)
                            .addComponent(jLabel20)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel18))
                                .addGap(53, 53, 53)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtFullnameEnglish, javax.swing.GroupLayout.DEFAULT_SIZE, 1022, Short.MAX_VALUE)
                                        .addComponent(txtFullNameSinhala)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(FatherWorkAddresstxt, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(FatherWorkPlacetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(FatherJobtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(FatherNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel19)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(FatherHomeTelephonetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(38, 38, 38)
                                                    .addComponent(jLabel21)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(FatherMobiletxt, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(MotherWorkAddresstxt, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(MotherWorkPlacetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(MotherJobtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(MotherNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel26)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(MotherWorkTelephonetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jLabel24)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(MotherHomeTelephonetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jLabel25)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(MotherMobiletxt, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addComponent(txtAdmissionNo, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNameWithInitial, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dchBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(cboReligion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton4))
                                        .addComponent(txtClassOfAdmission, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dchDateOfAdmission, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(cboHouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton5))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(txtTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(164, 164, 164)
                                            .addComponent(jLabel31)
                                            .addGap(18, 18, 18)
                                            .addComponent(cboGramaVasama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton2)
                                            .addGap(127, 127, 127)
                                            .addComponent(jLabel32)
                                            .addGap(18, 18, 18)
                                            .addComponent(cboComeToSchoolBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton3))
                                        .addComponent(txtAddress)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(94, 94, 94)
                                                    .addComponent(rdoFemale))
                                                .addComponent(rdoMale))
                                            .addGap(230, 230, 230)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(FatherWorkTelephonetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(BroSis2AdmissionNumbertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BroSis3AdmissionNumbertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BroSis4AdmissionNumbertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BroSis5AdmissionNumbertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel30)
                                    .addComponent(BroSis1AdmissionNumbertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BroSis1Nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BroSis2Nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BroSis3Nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BroSis4Nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BroSis5Nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(274, 274, 274)
                                        .addComponent(jLabel1))))
                            .addComponent(jLabel7)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel27)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel27)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtAdmissionNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFullnameEnglish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNameWithInitial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtFullNameSinhala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(rdoMale)
                            .addComponent(rdoFemale))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dchBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31)
                            .addComponent(cboGramaVasama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32)
                            .addComponent(cboComeToSchoolBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(dchDateOfAdmission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(cboHouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(cboReligion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(txtClassOfAdmission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(413, 413, 413)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(FatherNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MotherNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(FatherJobtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MotherJobtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addGap(19, 19, 19)
                                .addComponent(jLabel16))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(FatherWorkPlacetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(MotherWorkPlacetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FatherWorkAddresstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MotherWorkAddresstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(FatherWorkTelephonetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(FatherMobiletxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel21)
                                .addComponent(MotherWorkTelephonetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel26)
                                .addComponent(MotherHomeTelephonetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel24)
                                .addComponent(MotherMobiletxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel25)
                                .addComponent(jLabel22))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(FatherHomeTelephonetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18)))
                .addGap(65, 65, 65)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BroSis1Nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BroSis1AdmissionNumbertxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BroSis2Nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BroSis2AdmissionNumbertxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BroSis3Nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BroSis3AdmissionNumbertxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BroSis4Nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BroSis4AdmissionNumbertxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BroSis5Nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BroSis5AdmissionNumbertxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(jButton1))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1066, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAdmissionNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdmissionNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdmissionNoActionPerformed
    public JButton getButton() {
        return btnAdd;
    }
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if ("".equals(txtAdmissionNo.getText())) {
            txtAdmissionNo.setText(JOptionPane.showInputDialog("Enter the admission number"));
        }
        if (!"".equals(txtAdmissionNo.getText())) {

            if ("".equals(txtFullnameEnglish.getText())) {
                txtFullnameEnglish.setText(JOptionPane.showInputDialog("Enter full name in English"));
            }
            if (!"".equals(txtFullnameEnglish.getText())) {
                if (rdoMale.isSelected() || rdoFemale.isSelected()) {

                    if (dchBirthDate.getDate().getTime() > new java.util.Date().getTime() | dchDateOfAdmission.getDate().getTime() > new java.util.Date().getTime()) {
                        if (JOptionPane.showConfirmDialog(rootPane, "Are you sure you entered correct dates", "Wrong Dates", JOptionPane.YES_OPTION, JOptionPane.WARNING_MESSAGE) != JOptionPane.YES_OPTION) {
                            return;
                        }
                    }

                    try {
                        if (notificationMode) {
                            saveOrUpdateStudent();
                            notificationDao.notifyTeacher(NIC, true);
                            JOptionPane.showMessageDialog(rootPane, "Sent for confirmation");

                        } else {
                            saveOrUpdateStudent();
                            JOptionPane.showMessageDialog(rootPane, "Saved succesfully");
                        }
                        this.dispose();

                    } catch (SQLException ex) {
                        Logger.getLogger(AddOrEditStudent.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(rdoFemale, "Select the gender");
                }

            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtFullnameEnglishKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFullnameEnglishKeyReleased
        fillNameWithInitial();
    }//GEN-LAST:event_txtFullnameEnglishKeyReleased

    private void FatherJobtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FatherJobtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FatherJobtxtActionPerformed

    private void FatherHomeTelephonetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FatherHomeTelephonetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FatherHomeTelephonetxtActionPerformed

    private void MotherHomeTelephonetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MotherHomeTelephonetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MotherHomeTelephonetxtActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if (jComboBox1.getSelectedIndex() == 0) {
            jLabel8.setVisible(true);
            MotherNametxt.setVisible(true);
            MotherJobtxt.setVisible(true);
            MotherWorkPlacetxt.setVisible(true);
            MotherWorkAddresstxt.setVisible(true);
            jLabel26.setVisible(true);
            MotherWorkTelephonetxt.setVisible(true);
            jLabel24.setVisible(true);
            MotherHomeTelephonetxt.setVisible(true);
            jLabel25.setVisible(true);
            MotherMobiletxt.setVisible(true);
        } else if (jComboBox1.getSelectedIndex() == 1) {
            jLabel8.setVisible(false);
            jLabel25.setVisible(false);
            jLabel24.setVisible(false);
            jLabel26.setVisible(false);
            MotherNametxt.setVisible(false);
            MotherJobtxt.setVisible(false);
            MotherWorkPlacetxt.setVisible(false);
            MotherWorkAddresstxt.setVisible(false);
            MotherWorkTelephonetxt.setVisible(false);
            MotherHomeTelephonetxt.setVisible(false);
            MotherMobiletxt.setVisible(false);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void FatherWorkTelephonetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FatherWorkTelephonetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FatherWorkTelephonetxtActionPerformed

    private void BroSis1AdmissionNumbertxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BroSis1AdmissionNumbertxtActionPerformed
        BroSis1AdmissionNumbertxtFocusLost(null);
    }//GEN-LAST:event_BroSis1AdmissionNumbertxtActionPerformed

    private void BroSis1AdmissionNumbertxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BroSis1AdmissionNumbertxtFocusLost
        try {
            Student B_or_S = studentDAO.getStudentObject(BroSis1AdmissionNumbertxt.getText());
            if (B_or_S != null) {
                BroSis1Nametxt.setText(B_or_S.getFullNameEnglish());
            }
        } catch (SQLException ex) {
            Logger.getLogger(AddOrEditStudent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BroSis1AdmissionNumbertxtFocusLost

    private void BroSis2AdmissionNumbertxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BroSis2AdmissionNumbertxtFocusLost
        try {
            Student B_or_S = studentDAO.getStudentObject(BroSis2AdmissionNumbertxt.getText());
            if (B_or_S != null) {
                BroSis2Nametxt.setText(B_or_S.getFullNameEnglish());
            }
        } catch (SQLException ex) {
            Logger.getLogger(AddOrEditStudent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BroSis2AdmissionNumbertxtFocusLost

    private void BroSis2AdmissionNumbertxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BroSis2AdmissionNumbertxtActionPerformed
        BroSis2AdmissionNumbertxtFocusLost(null);
    }//GEN-LAST:event_BroSis2AdmissionNumbertxtActionPerformed

    private void BroSis3AdmissionNumbertxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BroSis3AdmissionNumbertxtFocusLost
        try {
            Student B_or_S = studentDAO.getStudentObject(BroSis3AdmissionNumbertxt.getText());
            if (B_or_S != null) {
                BroSis3Nametxt.setText(B_or_S.getFullNameEnglish());
            }
        } catch (SQLException ex) {
            Logger.getLogger(AddOrEditStudent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BroSis3AdmissionNumbertxtFocusLost

    private void BroSis3AdmissionNumbertxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BroSis3AdmissionNumbertxtActionPerformed
        BroSis3AdmissionNumbertxtFocusLost(null);
    }//GEN-LAST:event_BroSis3AdmissionNumbertxtActionPerformed

    private void BroSis4AdmissionNumbertxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BroSis4AdmissionNumbertxtFocusLost
        try {
            Student B_or_S = studentDAO.getStudentObject(BroSis4AdmissionNumbertxt.getText());
            if (B_or_S != null) {
                BroSis4Nametxt.setText(B_or_S.getFullNameEnglish());
            }
        } catch (SQLException ex) {
            Logger.getLogger(AddOrEditStudent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BroSis4AdmissionNumbertxtFocusLost

    private void BroSis4AdmissionNumbertxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BroSis4AdmissionNumbertxtActionPerformed
        BroSis4AdmissionNumbertxtFocusLost(null);
    }//GEN-LAST:event_BroSis4AdmissionNumbertxtActionPerformed

    private void BroSis5AdmissionNumbertxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BroSis5AdmissionNumbertxtFocusLost
        try {
            Student B_or_S = studentDAO.getStudentObject(BroSis5AdmissionNumbertxt.getText());
            if (B_or_S != null) {
                BroSis5Nametxt.setText(B_or_S.getFullNameEnglish());
            }
        } catch (SQLException ex) {
            Logger.getLogger(AddOrEditStudent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BroSis5AdmissionNumbertxtFocusLost

    private void BroSis5AdmissionNumbertxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BroSis5AdmissionNumbertxtActionPerformed
        BroSis5AdmissionNumbertxtFocusLost(null);
    }//GEN-LAST:event_BroSis5AdmissionNumbertxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (JOptionPane.showConfirmDialog(rootPane, "All the details you have added will not be saved. Are you sure you want to close this?","Not saved",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE) == JOptionPane.YES_OPTION) {
            if (notificationMode) {
                try {
                    notificationDao.notifyTeacher(NIC, false);
                } catch (SQLException ex) {
                    Logger.getLogger(AddOrEditStudent.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            this.dispose();
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void FatherWorkTelephonetxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FatherWorkTelephonetxtFocusLost
        if (!isValidTel(FatherWorkTelephonetxt.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Telephone number you entered last is incorrect!", "Number Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_FatherWorkTelephonetxtFocusLost

    private void txtTelephoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelephoneFocusLost
        if (!isValidTel(txtTelephone.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Telephone number you entered last is incorrect!", "Number Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtTelephoneFocusLost

    private void FatherHomeTelephonetxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FatherHomeTelephonetxtFocusLost
        if (!isValidTel(FatherHomeTelephonetxt.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Telephone number you entered last is incorrect!", "Number Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_FatherHomeTelephonetxtFocusLost

    private void FatherMobiletxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FatherMobiletxtFocusLost
        if (!isValidTel(FatherMobiletxt.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Telephone number you entered last is incorrect!", "Number Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_FatherMobiletxtFocusLost

    private void MotherWorkTelephonetxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MotherWorkTelephonetxtFocusLost
        if (!isValidTel(MotherWorkTelephonetxt.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Telephone number you entered last is incorrect!", "Number Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_MotherWorkTelephonetxtFocusLost

    private void MotherHomeTelephonetxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MotherHomeTelephonetxtFocusLost
        if (!isValidTel(MotherHomeTelephonetxt.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Telephone number you entered last is incorrect!", "Number Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_MotherHomeTelephonetxtFocusLost

    private void MotherMobiletxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MotherMobiletxtFocusLost
        if (!isValidTel(MotherMobiletxt.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Telephone number you entered last is incorrect!", "Number Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_MotherMobiletxtFocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            SetGramaVasam();
        } catch (IOException ex) {
            Logger.getLogger(AddOrEditStudent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddOrEditStudent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            SetReligions();
        } catch (IOException ex) {
            Logger.getLogger(AddOrEditStudent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddOrEditStudent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            SetComeToSchoolBy();
        } catch (IOException ex) {
            Logger.getLogger(AddOrEditStudent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddOrEditStudent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            SetHouses();
        } catch (IOException ex) {
            Logger.getLogger(AddOrEditStudent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddOrEditStudent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void dchBirthDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dchBirthDatePropertyChange

    }//GEN-LAST:event_dchBirthDatePropertyChange

    private void dchBirthDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dchBirthDateFocusLost

    }//GEN-LAST:event_dchBirthDateFocusLost

    private void dchDateOfAdmissionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dchDateOfAdmissionFocusLost

    }//GEN-LAST:event_dchDateOfAdmissionFocusLost

    public void saveOrUpdateStudent() throws SQLException {

        String admissionNumber = txtAdmissionNo.getText();
        String fullNameEnglish = txtFullnameEnglish.getText();
        String fullNameSinhala = txtFullNameSinhala.getText();
        String nameWithInitials = txtNameWithInitial.getText();
        Date birthDate;

        try {
            birthDate = new java.sql.Date(dchBirthDate.getDate().getTime());
        } catch (NullPointerException e) {
            birthDate = null;
        }

        String house = cboHouse.getSelectedItem().toString();
        String religion = cboReligion.getSelectedItem().toString();
        String address = txtAddress.getText();
        String telephoneNumber = txtTelephone.getText();
        Date dateOfAdmission;
        try {
            dateOfAdmission = new java.sql.Date(dchDateOfAdmission.getDate().getTime());
        } catch (NullPointerException e) {
            dateOfAdmission = null;
        }
        String classOfAdmission = txtClassOfAdmission.getText();

        String gender = null;
        if (rdoMale.isSelected()) {
            gender = "Male";
        } else if (rdoFemale.isSelected()) {
            gender = "Female";
        }

        String gramaNiladhariVasama = cboGramaVasama.getSelectedItem().toString();
        String comeToSchoolBy = cboComeToSchoolBy.getSelectedItem().toString();

        int familyKey;//this value is in the object and we don't change it

        //Check Father or guardian
        String fatherName;
        if (jComboBox1.getSelectedIndex() == 1) {
            fatherName = "**" + FatherNametxt.getText();
        } else {
            fatherName = FatherNametxt.getText();
        }
        String fatherJob = FatherJobtxt.getText();
        String fatherWorkPlace = FatherWorkPlacetxt.getText();
        String fatherWorkAddress = FatherWorkAddresstxt.getText();
        String fatherWorkTelephone = FatherWorkTelephonetxt.getText();
        String fatherHomeTelephone = FatherHomeTelephonetxt.getText();
        String fatherMobile = FatherMobiletxt.getText();
        String motherName = MotherNametxt.getText();
        String motherJob = MotherJobtxt.getText();
        String motherWorkPlace = MotherWorkPlacetxt.getText();
        String motherWorkAddress = MotherWorkAddresstxt.getText();
        String motherWorkTelephone = MotherWorkTelephonetxt.getText();
        String motherHomeTelephone = MotherHomeTelephonetxt.getText();
        String motherMobile = MotherMobiletxt.getText();

        String broSis1AdmissionNumber = BroSis1AdmissionNumbertxt.getText();
        String broSis2AdmissionNumber = BroSis2AdmissionNumbertxt.getText();
        String broSis3AdmissionNumber = BroSis3AdmissionNumbertxt.getText();
        String broSis4AdmissionNumber = BroSis4AdmissionNumbertxt.getText();
        String broSis5AdmissionNumber = BroSis5AdmissionNumbertxt.getText();
        String broSis1Name = BroSis1Nametxt.getText();
        String broSis2Name = BroSis2Nametxt.getText();
        String broSis3Name = BroSis3Nametxt.getText();
        String broSis4Name = BroSis4Nametxt.getText();
        String broSis5Name = BroSis5Nametxt.getText();

        Student tempStudent = null;

        if (This_is_AddMode_but_not_EditMode) {
            familyKey = -1;//this value will never user because this is adding a new student
            tempStudent = new Student(admissionNumber, fullNameEnglish, fullNameSinhala, birthDate, house, religion, address, telephoneNumber, dateOfAdmission, classOfAdmission, gender, nameWithInitials, gramaNiladhariVasama, comeToSchoolBy, familyKey, fatherName, fatherJob, fatherWorkPlace, fatherWorkAddress, fatherWorkTelephone, fatherHomeTelephone, fatherMobile, motherName, motherJob, motherWorkPlace, motherWorkAddress, motherWorkTelephone, motherHomeTelephone, motherMobile, broSis1AdmissionNumber, broSis2AdmissionNumber, broSis3AdmissionNumber, broSis4AdmissionNumber, broSis5AdmissionNumber, broSis1Name, broSis2Name, broSis3Name, broSis4Name, broSis5Name, PasswordUtils.encryptPassword("1234"), 5);
            studentDAO.addStudent(tempStudent);

        } else if (!This_is_AddMode_but_not_EditMode) {
            tempStudent = selectedStudent;
            tempStudent.setAdmissionNumber(admissionNumber);
            tempStudent.setFullNameEnglish(fullNameEnglish);
            tempStudent.setFullNameSinhala(fullNameSinhala);
            tempStudent.setBirthDate(birthDate);
            tempStudent.setHouse(house);
            tempStudent.setReligion(religion);
            tempStudent.setAddress(address);
            tempStudent.setTelephoneNumber(telephoneNumber);
            tempStudent.setDateOfAdmission(dateOfAdmission);
            tempStudent.setClassOfAdmission(classOfAdmission);
            tempStudent.setGender(gender);
            tempStudent.setNameWithInitials(nameWithInitials);
            tempStudent.setGramaNiladhariVasama(gramaNiladhariVasama);
            tempStudent.setComeToSchoolBy(comeToSchoolBy);

            tempStudent.setFatherName(fatherName);
            tempStudent.setFatherJob(fatherJob);
            tempStudent.setFatherWorkPlace(fatherWorkPlace);
            tempStudent.setFatherWorkAddress(fatherWorkAddress);
            tempStudent.setFatherWorkTelephone(fatherWorkTelephone);
            tempStudent.setFatherHomeTelephone(fatherHomeTelephone);
            tempStudent.setFatherMobile(fatherMobile);
            tempStudent.setMotherName(motherName);
            tempStudent.setMotherJob(motherJob);
            tempStudent.setMotherWorkPlace(motherWorkPlace);
            tempStudent.setMotherWorkAddress(motherWorkAddress);
            tempStudent.setMotherWorkTelephone(motherWorkTelephone);
            tempStudent.setMotherHomeTelephone(motherHomeTelephone);
            tempStudent.setMotherMobile(motherMobile);

            tempStudent.setBroSis1AdmissionNumber(broSis1AdmissionNumber);
            tempStudent.setBroSis2AdmissionNumber(broSis2AdmissionNumber);
            tempStudent.setBroSis3AdmissionNumber(broSis3AdmissionNumber);
            tempStudent.setBroSis4AdmissionNumber(broSis4AdmissionNumber);
            tempStudent.setBroSis5AdmissionNumber(broSis5AdmissionNumber);
            tempStudent.setBroSis1Name(broSis1Name);
            tempStudent.setBroSis2Name(broSis2Name);
            tempStudent.setBroSis3Name(broSis3Name);
            tempStudent.setBroSis4Name(broSis4Name);
            tempStudent.setBroSis5Name(broSis5Name);

            if (accessPriviledge == 1) {
                Notification notification = new Notification(teacher.getNIC(), teacher.getNameWithin(), "Student", selectedStudent.getFullNameEnglish(), selectedStudent);
                notificationDao.setStudent(selectedStudent);
                notificationDao.addNotification(notification);

                System.out.println("accessGained:" + notification.getTypeOfPersonGoingToBeChanged());
            } else {
                studentDAO.updateStudent(tempStudent, previousAdmissionNumber);
                activitiesDAO.updateAdmissionNumber(admissionNumber, previousAdmissionNumber);
            }
        }
    }

    public void SetGramaVasam() throws IOException, SQLException {
        cboGramaVasama.removeAllItems();
        List<String> divisionList = new GramaNiladhariDivisionsDAO().getGramaNiladhariDivisions();
        cboGramaVasama.addItem("-----");
        for (int i = 0; i < divisionList.size(); i++) {
            cboGramaVasama.addItem(divisionList.get(i));
        }
        cboGramaVasama.setSelectedItem(selectedStudent.getGramaNiladhariVasama());
    }

    public void SetReligions() throws IOException, SQLException {
        cboReligion.removeAllItems();
        List<String> religionList = new ReligionsDAO().getReligions();
        cboReligion.addItem("-----");
        for (int i = 0; i < religionList.size(); i++) {
            cboReligion.addItem(religionList.get(i));
        }
        cboReligion.setSelectedItem(selectedStudent.getReligion());
    }

    public void SetHouses() throws IOException, SQLException {
        cboHouse.removeAllItems();
        List<String> houseList = new HousesDAO().getHouses();
        cboHouse.addItem("-----");
        for (String houseListItem : houseList) {
            cboHouse.addItem(houseListItem);
        }
        cboHouse.setSelectedItem(selectedStudent.getHouse());
    }

    public void SetComeToSchoolBy() throws IOException, SQLException {
        cboComeToSchoolBy.removeAllItems();
        List<String> comeToSchoolByList = new ComeToSchoolByDAO().getComeToSchoolBy();
        cboComeToSchoolBy.addItem("-----");
        for (int i = 0; i < comeToSchoolByList.size(); i++) {
            cboComeToSchoolBy.addItem(comeToSchoolByList.get(i));
        }
        cboComeToSchoolBy.setSelectedItem(selectedStudent.getComeToSchoolBy());
    }

    public void populateData(Student student) throws IOException, SQLException {

        SetGramaVasam();
        SetReligions();
        SetComeToSchoolBy();
        SetHouses();

        txtAdmissionNo.setText(student.getAdmissionNumber());
        txtFullnameEnglish.setText(student.getFullNameEnglish());
        txtFullNameSinhala.setText(student.getFullNameSinhala());
        dchBirthDate.setDate(student.getBirthDate());
        cboHouse.setSelectedItem(student.getHouse());
        cboReligion.setSelectedItem(student.getReligion());
        txtAddress.setText(student.getAddress());
        txtTelephone.setText(student.getTelephoneNumber());
        dchDateOfAdmission.setDate(student.getDateOfAdmission());
        txtClassOfAdmission.setText(student.getClassOfAdmission());
        txtNameWithInitial.setText(student.getNameWithInitials());
        String gender = student.getGender();
        switch (gender) {
            case "Male":
                rdoMale.setSelected(true);
                break;
            case "Female":
                rdoFemale.setSelected(true);
                break;
        }

        cboGramaVasama.setSelectedItem(student.getGramaNiladhariVasama());
        cboComeToSchoolBy.setSelectedItem(student.getComeToSchoolBy());

        String fathername = student.getFatherName();
        if (fathername.substring(0, 2).equals("**")) {
            jComboBox1.setSelectedIndex(1);
            jComboBox1ActionPerformed(null);
        }
        FatherNametxt.setText(fathername.substring(2));

        FatherJobtxt.setText(student.getFatherJob());
        FatherWorkPlacetxt.setText(student.getFatherWorkPlace());
        FatherWorkAddresstxt.setText(student.getFatherWorkAddress());
        FatherWorkTelephonetxt.setText(student.getFatherWorkTelephone());
        FatherHomeTelephonetxt.setText(student.getFatherHomeTelephone());
        FatherMobiletxt.setText(student.getFatherMobile());
        MotherNametxt.setText(student.getMotherName());
        MotherJobtxt.setText(student.getMotherJob());
        MotherWorkPlacetxt.setText(student.getMotherWorkPlace());
        MotherWorkAddresstxt.setText(student.getMotherWorkAddress());
        MotherWorkTelephonetxt.setText(student.getMotherWorkTelephone());
        MotherHomeTelephonetxt.setText(student.getMotherHomeTelephone());
        MotherMobiletxt.setText(student.getMotherMobile());

        BroSis1AdmissionNumbertxt.setText(student.getBroSis1AdmissionNumber());
        BroSis2AdmissionNumbertxt.setText(student.getBroSis2AdmissionNumber());
        BroSis3AdmissionNumbertxt.setText(student.getBroSis3AdmissionNumber());
        BroSis4AdmissionNumbertxt.setText(student.getBroSis4AdmissionNumber());
        BroSis5AdmissionNumbertxt.setText(student.getBroSis5AdmissionNumber());
        BroSis1Nametxt.setText(student.getBroSis1Name());
        BroSis2Nametxt.setText(student.getBroSis2Name());
        BroSis3Nametxt.setText(student.getBroSis3Name());
        BroSis4Nametxt.setText(student.getBroSis4Name());
        BroSis5Nametxt.setText(student.getBroSis5Name());

    }

    void fillNameWithInitial() {
        String tempName = txtFullnameEnglish.getText();
        String[] nameList = tempName.split(" ");
        String nameWithInitial = "";
        for (int ui = 0; ui < nameList.length - 1; ui++) {
            nameWithInitial += nameList[ui].substring(0, 1) + ". ";
        }
        nameWithInitial += nameList[nameList.length - 1];

        txtNameWithInitial.setText(nameWithInitial);
    }

    public boolean isValidTel(String number) {
        return validater.isValidTelNO(number);
    }

    public void setAccessPriviledge() {
        this.accessPriviledge = 1;
    }

    public void setTeacher(Teacher teacher) {
        this.teacher = teacher;
    }

    public void setNotificationMode() {
        this.notificationMode = true;
    }

    public void setAddButtonName(String name) {
        btnAdd.setText(name);
    }

    public void setCancelButtonName(String name) {
        jButton1.setText(name);
    }

    public void setNIC(String NIC) {
        this.NIC = NIC;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BroSis1AdmissionNumbertxt;
    private javax.swing.JTextField BroSis1Nametxt;
    private javax.swing.JTextField BroSis2AdmissionNumbertxt;
    private javax.swing.JTextField BroSis2Nametxt;
    private javax.swing.JTextField BroSis3AdmissionNumbertxt;
    private javax.swing.JTextField BroSis3Nametxt;
    private javax.swing.JTextField BroSis4AdmissionNumbertxt;
    private javax.swing.JTextField BroSis4Nametxt;
    private javax.swing.JTextField BroSis5AdmissionNumbertxt;
    private javax.swing.JTextField BroSis5Nametxt;
    private javax.swing.JTextField FatherHomeTelephonetxt;
    private javax.swing.JTextField FatherJobtxt;
    private javax.swing.JTextField FatherMobiletxt;
    private javax.swing.JTextField FatherNametxt;
    private javax.swing.JTextField FatherWorkAddresstxt;
    private javax.swing.JTextField FatherWorkPlacetxt;
    private javax.swing.JTextField FatherWorkTelephonetxt;
    private javax.swing.JTextField MotherHomeTelephonetxt;
    private javax.swing.JTextField MotherJobtxt;
    private javax.swing.JTextField MotherMobiletxt;
    private javax.swing.JTextField MotherNametxt;
    private javax.swing.JTextField MotherWorkAddresstxt;
    private javax.swing.JTextField MotherWorkPlacetxt;
    private javax.swing.JTextField MotherWorkTelephonetxt;
    private javax.swing.JButton btnAdd;
    private javax.swing.ButtonGroup buttonGroupGender;
    private javax.swing.JComboBox cboComeToSchoolBy;
    private javax.swing.JComboBox cboGramaVasama;
    private javax.swing.JComboBox cboHouse;
    private javax.swing.JComboBox cboReligion;
    private com.toedter.calendar.JDateChooser dchBirthDate;
    private com.toedter.calendar.JDateChooser dchDateOfAdmission;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdoFemale;
    private javax.swing.JRadioButton rdoMale;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAdmissionNo;
    private javax.swing.JTextField txtClassOfAdmission;
    private javax.swing.JTextField txtFullNameSinhala;
    private javax.swing.JTextField txtFullnameEnglish;
    private javax.swing.JTextField txtNameWithInitial;
    private javax.swing.JTextField txtTelephone;
    // End of variables declaration//GEN-END:variables
}
