package chanaka.gui;

import chanaka.dao.ActivitiesDAO;
import chanaka.data.Student;
import chanaka.pdf.PdfCreator;
import com.itextpdf.text.DocumentException;
import java.io.FileNotFoundException;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Certificate extends javax.swing.JDialog {

    Student student;
    Connection myConn;
    ActivitiesDAO activitiesDAO;

    /**
     * Creates new form Certificate
     *
     * @param parent
     * @param modal
     * @param student
     * @param myConn
     * @throws java.sql.SQLException
     */
    public Certificate(java.awt.Frame parent, boolean modal, Student student, Connection myConn) throws SQLException {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.student = student;
        this.myConn = myConn;
        this.activitiesDAO = new ActivitiesDAO(myConn);
        populate();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        FullNameSinhalatxt = new javax.swing.JTextField();
        YearOfAdmissiontxt = new javax.swing.JTextField();
        ClassOfAdmissiontxt = new javax.swing.JTextField();
        AdmissionNumbertxt = new javax.swing.JTextField();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Clubtxt = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        Othertxt = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        Sportstxt = new javax.swing.JTextArea();
        btnCreatePDF = new javax.swing.JButton();
        Todaydco = new com.toedter.calendar.JDateChooser();
        btnSaveClub = new javax.swing.JButton();
        btnSaveSports = new javax.swing.JButton();
        btnSaveOther = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("සහතික");
        setFont(new java.awt.Font("Iskoola Pota", 0, 10)); // NOI18N
        setPreferredSize(new java.awt.Dimension(787, 700));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(787, 1056));

        jPanel3.setFont(new java.awt.Font("Iskoola Pota", 0, 11)); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(787, 1139));

        jLabel63.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel63.setText("Full name :");

        jLabel64.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel64.setText("Year of admission :");

        jLabel65.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel65.setText("Class of admission :");

        jLabel66.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel66.setText("Admission number :");

        FullNameSinhalatxt.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N

        YearOfAdmissiontxt.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N

        ClassOfAdmissiontxt.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N

        AdmissionNumbertxt.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        AdmissionNumbertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdmissionNumbertxtActionPerformed(evt);
            }
        });

        jLabel75.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel75.setText("Clubs and societies");

        jLabel76.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel76.setText("Other:");

        jLabel77.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel77.setText("Sports :");

        jLabel91.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel91.setText("Date :");

        jLabel93.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jLabel93.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel93.setText("Leaving Certificate");

        Clubtxt.setColumns(20);
        Clubtxt.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        Clubtxt.setRows(5);
        jScrollPane2.setViewportView(Clubtxt);

        Othertxt.setColumns(20);
        Othertxt.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        Othertxt.setRows(5);
        jScrollPane3.setViewportView(Othertxt);

        Sportstxt.setColumns(20);
        Sportstxt.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        Sportstxt.setRows(5);
        jScrollPane4.setViewportView(Sportstxt);

        btnCreatePDF.setText("Leaving Certificate PDF");
        btnCreatePDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePDFActionPerformed(evt);
            }
        });

        Todaydco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TodaydcoMouseClicked(evt);
            }
        });

        btnSaveClub.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        btnSaveClub.setText("Save");
        btnSaveClub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveClubActionPerformed(evt);
            }
        });

        btnSaveSports.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        btnSaveSports.setText("Save");
        btnSaveSports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveSportsActionPerformed(evt);
            }
        });

        btnSaveOther.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        btnSaveOther.setText("Save");
        btnSaveOther.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveOtherActionPerformed(evt);
            }
        });

        jButton1.setText("Character certificate PDF");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel93, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(279, 279, 279))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel77))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnSaveClub)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel75))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel91)
                                    .addComponent(jLabel76)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Todaydco, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnSaveOther)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(btnCreatePDF)
                                        .addGap(39, 39, 39)
                                        .addComponent(jButton1))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel64)
                                        .addGap(122, 122, 122)
                                        .addComponent(YearOfAdmissiontxt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel65)
                                            .addComponent(jLabel66))
                                        .addGap(118, 118, 118)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ClassOfAdmissiontxt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(AdmissionNumbertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel63)
                                        .addGap(169, 169, 169)
                                        .addComponent(FullNameSinhalatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnSaveSports)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel93)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel63))
                    .addComponent(FullNameSinhalatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel64))
                    .addComponent(YearOfAdmissiontxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel65))
                    .addComponent(ClassOfAdmissiontxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel66))
                    .addComponent(AdmissionNumbertxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jLabel75)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSaveClub, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel77)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSaveSports, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jLabel76)
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Todaydco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSaveOther, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel91)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreatePDF)
                    .addComponent(jButton1))
                .addGap(26, 26, 26))
        );

        jScrollPane1.setViewportView(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreatePDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePDFActionPerformed
        int returnedValue = JOptionPane.showConfirmDialog(rootPane, "Do you want to save details");
        if (returnedValue == JOptionPane.YES_OPTION) {
            btnSaveClubActionPerformed(evt);
            btnSaveSportsActionPerformed(evt);
            btnSaveOtherActionPerformed(evt);
        }
        if (returnedValue != JOptionPane.CANCEL_OPTION) {
            PdfCreator pdfCreator = new PdfCreator(student, activitiesDAO);
            try {
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String date = sdf.format(Todaydco.getDate());

                pdfCreator.createLeavingCertificatePDF(date);
                JOptionPane.showMessageDialog(rootPane, "PDF is created. go to the Directory");
                this.dispose();
            } catch (FileNotFoundException | DocumentException | SQLException ex) {
                Logger.getLogger(Certificate.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnCreatePDFActionPerformed

    private void AdmissionNumbertxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdmissionNumbertxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdmissionNumbertxtActionPerformed

    private void TodaydcoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TodaydcoMouseClicked

    }//GEN-LAST:event_TodaydcoMouseClicked

    private void btnSaveClubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveClubActionPerformed
        try {
            activitiesDAO.updateClubRecord(student.getAdmissionNumber(), Clubtxt.getText());
        } catch (SQLException ex) {
            Logger.getLogger(Certificate.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSaveClubActionPerformed

    private void btnSaveSportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveSportsActionPerformed
        try {
            activitiesDAO.updateSportsRecord(student.getAdmissionNumber(), Sportstxt.getText());
        } catch (SQLException ex) {
            Logger.getLogger(Certificate.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSaveSportsActionPerformed

    private void btnSaveOtherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveOtherActionPerformed
        try {
            activitiesDAO.updateDisciplineRecord(student.getAdmissionNumber(), Othertxt.getText());
        } catch (SQLException ex) {
            Logger.getLogger(Certificate.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSaveOtherActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int returnedValue = JOptionPane.showConfirmDialog(rootPane, "Do you want to save details");
        if (returnedValue == JOptionPane.YES_OPTION) {
            btnSaveClubActionPerformed(evt);
            btnSaveSportsActionPerformed(evt);
            btnSaveOtherActionPerformed(evt);
        }
        if (returnedValue != JOptionPane.CANCEL_OPTION) {
            PdfCreator pdfCreator = new PdfCreator(student, activitiesDAO);
            try {
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String date = sdf.format(Todaydco.getDate());

                pdfCreator.createCharacterCertificatePDF(date);
                JOptionPane.showMessageDialog(rootPane, "PDF is created. go to the Directory");
                this.dispose();
            } catch (FileNotFoundException | DocumentException | SQLException ex) {
                Logger.getLogger(Certificate.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void populate() throws SQLException {
        FullNameSinhalatxt.setText(student.getFullNameEnglish());

        YearOfAdmissiontxt.setText(Integer.toString(student.getDateOfAdmission().getYear() + 1900));
        //not sure this code

        ClassOfAdmissiontxt.setText(student.getClassOfAdmission());
        AdmissionNumbertxt.setText(student.getAdmissionNumber());
        Clubtxt.setText(activitiesDAO.getClubRecord(student.getAdmissionNumber()));
        Sportstxt.setText(activitiesDAO.getSportsRecord(student.getAdmissionNumber()));
        Othertxt.setText(activitiesDAO.getDisciplineRecord(student.getAdmissionNumber()));
        Todaydco.setDate(new Date());
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AdmissionNumbertxt;
    private javax.swing.JTextField ClassOfAdmissiontxt;
    private javax.swing.JTextArea Clubtxt;
    private javax.swing.JTextField FullNameSinhalatxt;
    private javax.swing.JTextArea Othertxt;
    private javax.swing.JTextArea Sportstxt;
    private com.toedter.calendar.JDateChooser Todaydco;
    private javax.swing.JTextField YearOfAdmissiontxt;
    private javax.swing.JButton btnCreatePDF;
    private javax.swing.JButton btnSaveClub;
    private javax.swing.JButton btnSaveOther;
    private javax.swing.JButton btnSaveSports;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables

}
