/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chamin.gui;

import chamin.dao.BookDAO;
import chamin.dao.ClubDAO;
import chamin.dao.DbConnector;
import chamin.data.Book;
import chanaka.dao.StudentDAO;
import chanaka.data.Student;
import chanaka.gui.AddOrEditStudent;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import prabath.dao.TeacherDAO;
import prabath.data.Teacher;

/**
 *
 * @author Chamin
 */
public class bookTransaction extends javax.swing.JDialog {

    DbConnector dbConnector;

    TeacherDAO teacherDAO;
    StudentDAO studentDAO;
    BookDAO bookDAO;

    //some object parameters
    Book recievingBook = null;
    Book lendingBook = null;
    Student Sborrower = null;
    Teacher Tborrower = null;
    String bId = null;
    
    

    public bookTransaction() {
        initComponents();

        /*//set the form in mmdle of the window
         Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
         //this.setLocation(dim.width/2-this.getWidth()/2, dim.height/2-this.getHeight()/2);
         this.setSize(dim.width, dim.height - 40);
         */
        try {
            // create the central DAO
            dbConnector = new DbConnector();
            // make a DAO for Person class by sending in the DB Connection from dbConnector

            teacherDAO = new TeacherDAO(dbConnector.getMyConn());
            studentDAO = new StudentDAO(dbConnector.getMyConn());
            bookDAO = new BookDAO(dbConnector.getMyConn());
        } catch (IOException | SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex, "Error", JOptionPane.ERROR_MESSAGE);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lendPnl = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnLend = new javax.swing.JButton();
        receive4 = new javax.swing.JLabel();
        txtBookKeeperId1 = new javax.swing.JTextField();
        txtBookId1 = new javax.swing.JTextField();
        receive7 = new javax.swing.JLabel();
        btnSearch1 = new javax.swing.JButton();
        receive6 = new javax.swing.JLabel();
        receive8 = new javax.swing.JLabel();
        btnSearch2 = new javax.swing.JButton();
        comBox2 = new javax.swing.JComboBox();
        txtBookBorrowersId = new javax.swing.JTextField();
        txtBookBorrowerName3 = new javax.swing.JTextField();
        btnAddBook = new javax.swing.JButton();
        lbllbookName = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        receive = new javax.swing.JLabel();
        btnReceive = new javax.swing.JButton();
        txtBookId = new javax.swing.JTextField();
        receive1 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        receive2 = new javax.swing.JLabel();
        txtBookKeeperId = new javax.swing.JTextField();
        txtBookKeeperName = new javax.swing.JTextField();
        receive3 = new javax.swing.JLabel();
        comBox = new javax.swing.JComboBox();
        lblrbookName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Book Transaction");

        lendPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lendPnl.setVerifyInputWhenFocusTarget(false);

        jLabel1.setText("Lending");

        btnLend.setText("Lend");
        btnLend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLendActionPerformed(evt);
            }
        });

        receive4.setText("Current Keeper Index : ");

        txtBookKeeperId1.setEditable(false);
        txtBookKeeperId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBookKeeperId1ActionPerformed(evt);
            }
        });

        txtBookId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBookId1ActionPerformed(evt);
            }
        });

        receive7.setText("Book Index : ");

        btnSearch1.setText("Search");
        btnSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch1ActionPerformed(evt);
            }
        });

        receive6.setText("Borrower Index : ");

        receive8.setText("Borrower Name : ");

        btnSearch2.setText("Search");
        btnSearch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch2ActionPerformed(evt);
            }
        });

        comBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Student", "Teacher" }));

        txtBookBorrowersId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBookBorrowersIdActionPerformed(evt);
            }
        });

        txtBookBorrowerName3.setEditable(false);
        txtBookBorrowerName3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBookBorrowerName3ActionPerformed(evt);
            }
        });

        btnAddBook.setText("Add book");
        btnAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBookActionPerformed(evt);
            }
        });

        lbllbookName.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N

        javax.swing.GroupLayout lendPnlLayout = new javax.swing.GroupLayout(lendPnl);
        lendPnl.setLayout(lendPnlLayout);
        lendPnlLayout.setHorizontalGroup(
            lendPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lendPnlLayout.createSequentialGroup()
                .addGap(0, 235, Short.MAX_VALUE)
                .addGroup(lendPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lendPnlLayout.createSequentialGroup()
                        .addComponent(btnLend)
                        .addGap(266, 266, 266))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lendPnlLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(274, 274, 274))))
            .addGroup(lendPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lendPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(receive7)
                    .addComponent(receive4)
                    .addComponent(receive8)
                    .addComponent(receive6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lendPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbllbookName, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addGroup(lendPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtBookKeeperId1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                        .addComponent(txtBookId1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtBookBorrowersId)
                        .addComponent(txtBookBorrowerName3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lendPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lendPnlLayout.createSequentialGroup()
                        .addComponent(comBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(btnSearch2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(lendPnlLayout.createSequentialGroup()
                        .addComponent(btnSearch1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddBook)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lendPnlLayout.setVerticalGroup(
            lendPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lendPnlLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(lendPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBookId1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(receive7)
                    .addComponent(btnSearch1)
                    .addComponent(btnAddBook))
                .addGap(2, 2, 2)
                .addComponent(lbllbookName, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lendPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lendPnlLayout.createSequentialGroup()
                        .addGroup(lendPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBookKeeperId1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(receive4))
                        .addGap(18, 18, 18)
                        .addGroup(lendPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(receive6)
                            .addComponent(txtBookBorrowersId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lendPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSearch2)
                        .addComponent(comBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(lendPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(receive8)
                    .addComponent(txtBookBorrowerName3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(btnLend)
                .addGap(20, 20, 20))
        );

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.setPreferredSize(new java.awt.Dimension(551, 329));

        receive.setText("Receiving");

        btnReceive.setText("Receive");
        btnReceive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReceiveActionPerformed(evt);
            }
        });

        txtBookId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBookIdActionPerformed(evt);
            }
        });

        receive1.setText("Book Index : ");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        receive2.setText("Current Keeper Index : ");

        txtBookKeeperId.setEditable(false);
        txtBookKeeperId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBookKeeperIdActionPerformed(evt);
            }
        });

        txtBookKeeperName.setEditable(false);
        txtBookKeeperName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBookKeeperNameActionPerformed(evt);
            }
        });

        receive3.setText("Current Keeper Name : ");

        comBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Student", "Teacher" }));

        lblrbookName.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(receive)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(receive1)
                            .addComponent(receive3)
                            .addComponent(receive2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtBookKeeperName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBookId, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBookKeeperId, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblrbookName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(btnSearch)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(btnReceive)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(receive)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBookId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(comBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(receive1))
                .addGap(2, 2, 2)
                .addComponent(lblrbookName, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBookKeeperId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(receive2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBookKeeperName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(receive3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(btnReceive)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lendPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lendPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReceiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReceiveActionPerformed
        int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to release the keeper ? ", "Receiving", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            recievingBook.setKeeperId("");

            try {
                bookDAO.updateBook(recievingBook, recievingBook.getBooId());
                recievingClear2();
            } catch (SQLException ex) {
                //System.out.println("there is a error");

                JOptionPane.showMessageDialog(null, "Enter correct book id", "Error", JOptionPane.INFORMATION_MESSAGE);

            }

        }
    }//GEN-LAST:event_btnReceiveActionPerformed

    private void txtBookIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBookIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBookIdActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

        String boolId = txtBookId.getText();
        System.out.println(boolId);
        try {
            recievingClear();

            recievingBook = bookDAO.searchBook(boolId);
            lblrbookName.setText(recievingBook.getTitle());
            String keepersName = null;
            String keepersId = recievingBook.getKeeperId();
            if (!keepersId.equals("")) {
                txtBookKeeperId.setText(keepersId);
            } else {
                txtBookKeeperId.setText("Book is in the library.");
            }
            if (comBox.getSelectedItem().equals("Student")) {
                Student keeper = studentDAO.getStudentObject(keepersId);

                keepersName = keeper.getNameWithInitials();
            } else {
                Teacher keeper = teacherDAO.getTeacherById(keepersId);

                keepersName = keeper.getNameWithin();

            }

            txtBookKeeperName.setText(keepersName);

        } catch (SQLException ex) {
            lblrbookName.setText("Book ID is wrong or not in database");
            System.out.println("Ther is a sql error " + ex);
        } catch (NullPointerException ex) {
            if (comBox.getSelectedItem().equals("Student")) {
                txtBookKeeperName.setText("Current book keeper is not a student.");

            } else {
                txtBookKeeperName.setText("Current book keeper is not a teacher.");

            }
        }


    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtBookKeeperIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBookKeeperIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBookKeeperIdActionPerformed

    private void txtBookKeeperNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBookKeeperNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBookKeeperNameActionPerformed

    private void txtBookKeeperId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBookKeeperId1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBookKeeperId1ActionPerformed

    private void txtBookId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBookId1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBookId1ActionPerformed

    private void btnSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch1ActionPerformed

        String boolId = txtBookId1.getText();
        System.out.println(boolId);
        try {
            //lendindClear();

            lendingBook = bookDAO.searchBook(boolId);
            lbllbookName.setText(lendingBook.getTitle());
            //String keepersName = null;
            bId = lendingBook.getKeeperId();
            if (bId.equals("") || bId == null) {
                txtBookKeeperId1.setText("Book is in the library. No one keeps the book");
            } else {
                txtBookKeeperId1.setText(bId);
            }
            //lblLending.setText("");
        } catch (SQLException | NullPointerException ex) {
            txtBookKeeperId1.setText("There is no book with this index");

            System.out.println("Ther is a sql error " + ex);
        }


    }//GEN-LAST:event_btnSearch1ActionPerformed

    private void btnSearch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch2ActionPerformed
        try {
            String borrowerName = null;
            if (comBox2.getSelectedItem().equals("Student")) {
                Sborrower = studentDAO.getStudentObject(txtBookBorrowersId.getText());
                borrowerName = Sborrower.getNameWithInitials();
            } else {
                Tborrower = teacherDAO.getTeacherById(txtBookBorrowersId.getText());
                borrowerName = Tborrower.getNameWithin();
            }
            txtBookBorrowerName3.setText(borrowerName);

        } catch (SQLException | NullPointerException ex) {
            if (comBox2.getSelectedItem().equals("Student")) {
                txtBookBorrowerName3.setText("There is no student with this index");
            } else {
                txtBookBorrowerName3.setText("There is no teacher with this index");

            }
            System.out.println(ex);

        }

    }//GEN-LAST:event_btnSearch2ActionPerformed

    private void txtBookBorrowersIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBookBorrowersIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBookBorrowersIdActionPerformed

    private void txtBookBorrowerName3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBookBorrowerName3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBookBorrowerName3ActionPerformed

    private void btnLendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLendActionPerformed

        try {

            if (comBox2.getSelectedItem().equals("Student")) {
                bId = Sborrower.getAdmissionNumber();
            } else {
                bId = Tborrower.getNIC();
            }
            lendingBook.setKeeperId(bId);
            
             bookDAO.searchBook(lendingBook.getBooId());//for book ID
            
            int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to lend a book?", "Lending", JOptionPane.YES_NO_OPTION);
            if (dialogResult == JOptionPane.YES_OPTION) {
                bookDAO.updateBook(lendingBook, lendingBook.getBooId());
                Sborrower = null;
                Tborrower = null;
                lendingBook = null;
                lendindClear();
            }
        } catch (NullPointerException | SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Add correct book ID and borrower ID", "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnLendActionPerformed

    private void btnAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBookActionPerformed
         new AddBook(txtBookId1.getText()).setVisible(true);

        
        
    }//GEN-LAST:event_btnAddBookActionPerformed

    public void recievingClear() {
        //txtBookId.setText("");
        txtBookKeeperId.setText("");
        txtBookKeeperName.setText("");

    }
    public void recievingClear2() {
        txtBookId.setText("");
        txtBookKeeperId.setText("");
        txtBookKeeperName.setText("");

    }

    private void lendindClear() {
        //txtBookId.setText("");
        lbllbookName.setText("");
        txtBookId1.setText("");
        txtBookKeeperId1.setText("");
        txtBookBorrowersId.setText("");
        txtBookBorrowerName3.setText("");

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bookTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bookTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bookTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bookTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                bookTransaction dialog = new bookTransaction();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBook;
    private javax.swing.JButton btnLend;
    private javax.swing.JButton btnReceive;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearch1;
    private javax.swing.JButton btnSearch2;
    private javax.swing.JComboBox comBox;
    private javax.swing.JComboBox comBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbllbookName;
    private javax.swing.JLabel lblrbookName;
    private javax.swing.JPanel lendPnl;
    private javax.swing.JLabel receive;
    private javax.swing.JLabel receive1;
    private javax.swing.JLabel receive2;
    private javax.swing.JLabel receive3;
    private javax.swing.JLabel receive4;
    private javax.swing.JLabel receive6;
    private javax.swing.JLabel receive7;
    private javax.swing.JLabel receive8;
    private javax.swing.JTextField txtBookBorrowerName3;
    private javax.swing.JTextField txtBookBorrowersId;
    private javax.swing.JTextField txtBookId;
    private javax.swing.JTextField txtBookId1;
    private javax.swing.JTextField txtBookKeeperId;
    private javax.swing.JTextField txtBookKeeperId1;
    private javax.swing.JTextField txtBookKeeperName;
    // End of variables declaration//GEN-END:variables

}
